-- =============================================
-- 022 — "Food for the ..." content
-- =============================================
-- Curated Giggles stories + Thought dilemmas, plus the Thought vote.
-- All long-form content is GENERATED by a service-role edge function and is
-- INVISIBLE until an admin approves it (published = true). Reads are limited to
-- published rows; admins can see and manage everything via is_admin() (006).
-- Comments on dilemmas are a deliberate fast-follow — not in this migration.

-- ---- Giggles: original, wholesome, first-person retellings ----
CREATE TABLE IF NOT EXISTS curated_stories (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  kind TEXT NOT NULL DEFAULT 'giggle',       -- room to grow beyond giggles
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  category TEXT,
  published BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE curated_stories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "curated_read_published" ON curated_stories
  FOR SELECT USING (published = TRUE OR is_admin());
CREATE POLICY "curated_admin_update" ON curated_stories
  FOR UPDATE USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "curated_admin_delete" ON curated_stories
  FOR DELETE USING (is_admin());
-- Inserts come only from the service-role generator (bypasses RLS).

CREATE INDEX IF NOT EXISTS idx_curated_feed
  ON curated_stories (kind, created_at DESC) WHERE published = TRUE;
CREATE INDEX IF NOT EXISTS idx_curated_pending
  ON curated_stories (created_at) WHERE published = FALSE;

-- ---- Thought: original moral dilemmas ----
CREATE TABLE IF NOT EXISTS dilemmas (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  title TEXT NOT NULL,
  story TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE dilemmas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "dilemmas_read_published" ON dilemmas
  FOR SELECT USING (published = TRUE OR is_admin());
CREATE POLICY "dilemmas_admin_update" ON dilemmas
  FOR UPDATE USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "dilemmas_admin_delete" ON dilemmas
  FOR DELETE USING (is_admin());

CREATE INDEX IF NOT EXISTS idx_dilemmas_feed
  ON dilemmas (created_at DESC) WHERE published = TRUE;

-- ---- Thought: one anonymous vote per person ----
CREATE TABLE IF NOT EXISTS dilemma_votes (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  dilemma_id UUID REFERENCES dilemmas(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  choice TEXT NOT NULL CHECK (choice IN ('op_wrong','they_wrong','nobody','everyone')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (dilemma_id, user_id)   -- one vote each, structurally
);
ALTER TABLE dilemma_votes ENABLE ROW LEVEL SECURITY;

-- You can cast your own vote and read it back (to know you've voted / what).
-- You can NEVER read anyone else's raw vote — aggregates come from the RPC.
CREATE POLICY "votes_insert_own" ON dilemma_votes
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "votes_select_own" ON dilemma_votes
  FOR SELECT USING (auth.uid() = user_id);

-- Anonymous community split. SECURITY DEFINER so a member sees the percentages
-- without any access to individual votes.
CREATE OR REPLACE FUNCTION dilemma_results(p_dilemma_id UUID)
RETURNS TABLE (choice TEXT, votes BIGINT)
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT choice, COUNT(*)::BIGINT
  FROM dilemma_votes
  WHERE dilemma_id = p_dilemma_id
  GROUP BY choice;
$$;
GRANT EXECUTE ON FUNCTION dilemma_results(UUID) TO authenticated;
